export default {
  UPDATE_STORE: '',
  UPDATE_PROPERTY: 'UPDATE_PROPERTY',
  UPDATE_SYLLABUS_PROPERTY: 'UPDATE_SYLLABUS_PROPERTY',

  UPDATE_REQUEST_STATUS: 'UPDATE_REQUEST_STATUS',
  UPDATE_REQUEST_STATUS_SUCCESS: 'UPDATE_REQUEST_STATUS_SUCCESS',
  UPDATE_REQUEST_STATUS_FAILURE: 'UPDATE_REQUEST_STATUS_FAILURE',
};
